//ALL HEADER AND CPP(functions) FILES ARE INCULDED IN A FILE "all.h"
#include "imp1.h"
#include "StringtoStar.cpp"
#include "imp1.cpp"
#include "intro.cpp"
#include "ELvl1.cpp"
#include "mainmenudisplay.cpp"
#include "mainmenu.cpp"
#include "wordsfiling.cpp"
#include "border.cpp"
#include "timer.cpp"
#include "Elvl2.cpp"
#include "Elvl3.cpp"
#include "hlvl1.cpp"
#include "Hlvl2.cpp"
#include "help.cpp"
#include "aboutus.cpp"
#include "scoreboard.cpp"
